dhu = true
wired = "4e8:6860"
mitm = true
webserver = "0.0.0.0:8080"
ev = true
advertise = true
enable_btle = true
dongle_mode = false
debug = true
hexdump_level = "All"
disable_console_debug = true
legacy = true
quick_reconnect = false
bt_poweroff = false
connect = "00:00:00:00:00:00"
logfile = "/var/log/aa-proxy-rs.log"
stats_interval = 0
iface = "wlan0"
timeout_secs = 10
bt_timeout_secs = 120
dpi = 0
audio_max_unacked = 0
remove_tap_restriction = false
video_in_motion = false
disable_media_sink = false
disable_tts_sink = false
developer_mode = false
remove_bluetooth = false
remove_wifi = false
change_usb_order = false
stop_on_disconnect = false
waze_lht_workaround = false
ev_connector_types = ""
enable_ssh = true
usb_serial_console = false
wifi_version = 6
band = "5"
country_code = "US"
channel = 36
ssid = "aa-proxy"
wpa_passphrase = "aa-proxy"
eth_mode = ""
startup_delay = 0
ble_password = ""
external_antenna = false
# media_dump_base_port = 12345  # TCP port base for media stream tapping (mitm=true required)
